[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
